services:
  postgres:
    image: postgres:15-alpine
    container_name: rpg_postgres
    environment:
      POSTGRES_DB: rpg_db
      POSTGRES_USER: rpg_user  
      POSTGRES_PASSWORD: rpg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rpg_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpg_user -d rpg_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: rpg_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rpg_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Note: Server and client will run natively for development
  # Use: npm run dev (from root) to start both services

volumes:
  postgres_data:
  redis_data:

networks:
  rpg_network:
    driver: bridge
